# Development override - use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  boilerfab-service:
    environment:
      - DEBUG_MODE=true
      - LOG_LEVEL=DEBUG
      - AUTO_RELOAD=true
    volumes:
      # Add source code mounting for hot reloading
      - ../services/template_service:/app/services/template_service
      - ../:/app  # Mount entire source for development
    ports:
      - "8000:8000"
      - "5678:5678"  # Debug port
    command: uvicorn services.template_service.main:app --host 0.0.0.0 --port 8000 --reload --log-level debug
    
  # Enable Redis for caching in development
  redis:
    profiles: []  # Remove profile requirement for dev

  # Enable database for advanced features in development  
  postgres:
    profiles: []  # Remove profile requirement for dev