# Production override - use with: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

services:
  boilerfab-service:
    environment:
      - DEBUG_MODE=false
      - LOG_LEVEL=WARNING
      - AUTO_RELOAD=false
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    # Remove development volumes - use read-only in production
    volumes:
      - ../services:/app/services:ro
      - ../templates:/app/templates:ro  # Read-only in production
      - ../config/settings.yaml:/app/settings.yaml:ro
      - ../runtime/api_config.json:/app/api_config.json:ro
      - ../runtime/logs:/app/logs:rw
      - ../runtime/backups:/app/backups:rw

  # Lightweight monitoring in production
  dozzle:
    profiles: []  # Enable by default in production
    environment:
      - DOZZLE_LEVEL=warning  # Less verbose in prod
      
  uptime-kuma:
    profiles: []  # Enable by default in production