version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL={{#if (eq database_type "postgresql")}}postgresql://postgres:password@db:5432/{{PROJECT_NAME}}{{else}}sqlite:///./{{PROJECT_NAME}}.db{{/if}}
      - SECRET_KEY=your-secret-key-change-in-production
    depends_on:
      {{#if (eq database_type "postgresql")}}
      - db
      {{/if}}
    volumes:
      - ./app:/app/app
    restart: unless-stopped

  {{#if (eq database_type "postgresql")}}
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB={{PROJECT_NAME}}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
  {{/if}}